### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by AadeIT** [XiaoRobb/CarTeller#1]
您好，我在使用本项目发现直接运行manage.py无法运行成功是为什么？

在登陆时运行到 User.query.filter_by(username=username).first 就不动了，无法继续往下走，也不会报任何提示，我应该怎么做？

是我运行的方式不对吗？

python3  CarTeeler/CarTeller/manage.py

我该怎么办？

**Comment by AadeIT** [comment]
你好，您是否共享了您的权重

**Comment by XiaoRobb** [comment]
sorry，这个项目是一年前的了，最近也没有继续深度学习，这方面的知识有些遗忘了，当时提交上来的应该没有提交训练好的模型，我貌似记得这个代码也是没有包括训练的代码，只有使用的代码。这个项目环境的配置应该比较多，涉及到了多个第三方的库。抱歉，可能不能运行成功，现在也不能跟你解答问题出现在哪，可能是环境配置的问题，也可能是没有训练好的模型文件（我又去我的u盘找了找，训练好的模型、和训练代码没有找到了，抱歉），但是你可以参考一下，其实我们当时也是从零起步，参考大家的教程，完成的这个汽车识别的项目。网上的参考还是有很多的，你可以多多参考一些其他的文章或项目。

> 您好，我在使用本项目发现直接运行manage.py无法运行成功是为什么？
> 
> 在登陆时运行到 User.query.filter_by(username=username).first 就不动了，无法继续往下走，也不会报任何提示，我应该怎么做？
> 
> 是我运行的方式不对吗？
> 
> python3 CarTeeler/CarTeller/manage.py
> 
> 我该怎么办？

sorry，这个项目是一年前的了，最近也没有继续深度学习，这方面的知识有些遗忘了，当时提交上来的应该没有提交训练好的模型，我貌似记得这个代码也是没有包括训练的代码，只有使用的代码。这个项目环境的配置应该比较多，涉及到了多个第三方的库。抱歉，可能不能运行成功，现在也不能跟你解答问题出现在哪，可能是环境配置的问题，也可能是没有训练好的模型文件（我又去我的u盘找了找，训练好的模型、和训练代码没有找到了，抱歉），但是你可以参考一下，其实我们当时也是从零起步，参考大家的教程，完成的这个汽车识别的项目。网上的参考还是有很多的，你可以多多参考一些其他的文章或项目。

**Comment by AadeIT** [comment]
@XiaoRobb 好的谢谢
